# Espace Administration Globale (localhost, admin.localhost)
server {
    listen 80;
    server_name localhost admin.localhost;
    client_max_body_size 20M;

    root /var/www/html/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param HTTP_HOST $http_host;
        fastcgi_param SERVER_NAME $http_host;
    }
}

# Redirection dynamique par sous-domaine (*.localhost) vers les conteneurs des établissements
server {
    listen 80;
    server_name ~^(?<subdomain>[a-zA-Z0-9\-]+)\.localhost$;
    client_max_body_size 20M;

    location / {
        resolver 127.0.0.11 valid=30s;
        
        # Le nom du conteneur de l'établissement est par convention 'hotelixos-[subdomain]-app'
        proxy_pass http://hotelixos-$subdomain-app:80;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
